tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface": "#081a11",
        "primary": "#2ecc71",
        "tertiary": "#88c9a1",
        "surface-container-lowest": "#041009",
        "on-secondary-container": "#a8e6cf",
        "surface-variant": "#102b1c",
        "on-surface-variant": "#a3c2b1",
        "surface-container": "#0c2015",
        "secondary-container": "#183b27",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#c7f0d9",
        "on-tertiary-fixed-variant": "#2a543d",
        "tertiary-container": "#204b31",
        "inverse-primary": "#1b8a4a",
        "error": "#ff6b6b",
        "surface-bright": "#122a1d",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#0e2e1c",
        "secondary-fixed": "#bdf2dd",
        "tertiary-fixed-dim": "#a2dbbe",
        "primary-fixed": "#a3f0c3",
        "on-tertiary": "#000000",
        "primary-fixed-dim": "#70e09f",
        "error-container": "#521414",
        "outline-variant": "#1d3d2a",
        "on-surface": "#e0f2e9",
        "secondary-fixed-dim": "#8ee3c4",
        "secondary": "#4ea884",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#042e14",
        "surface-container-high": "#133120",
        "surface-container-low": "#0a1c13",
        "surface-tint": "#2ecc71",
        "surface-container-highest": "#173b27",
        "surface-dim": "#05140b",
        "on-tertiary-container": "#d1f5e0",
        "primary-container": "#1b5232",
        "background": "#041009",
        "inverse-surface": "#e0f2e9",
        "on-primary-fixed-variant": "#0d5c2c",
        "on-background": "#e0f2e9",
        "on-secondary-fixed": "#0a2618",
        "on-primary-container": "#b3f0cc",
        "inverse-on-surface": "#041009",
        "on-secondary-fixed-variant": "#12422a",
        "outline": "#3b6b4e",
        "on-primary": "#000000"
      },
      "borderRadius": {
        "DEFAULT": "0.5rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "2rem",
        "3xl": "2.5rem",
        "full": "9999px"
      },
      "fontFamily": {
        "display": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "title-lg": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"]
      }
    }
  }
};
